/**
 * Conversation titles.
 *
 * A title is generated by the model from the opening question, which means it
 * can be slow, wrong, or absent — so every path through here ends in something
 * printable. The database stores null for an unnamed conversation; the
 * placeholder below exists only for display.
 */

export const UNTITLED_CONVERSATION = "New conversation";

/** Roughly what a sidebar row shows before it clips. */
const MAX_TITLE_LENGTH = 60;

/**
 * The question itself, shortened. Used before the model has answered and again
 * whenever generation fails, so a conversation is never nameless for long.
 */
export function fallbackTitle(question: string): string {
  const cleaned = collapse(question);
  if (!cleaned) return UNTITLED_CONVERSATION;
  if (cleaned.length <= MAX_TITLE_LENGTH) return cleaned;

  // Cut on a word boundary when one is near the limit; mid-word truncation
  // reads as damage rather than as shortening.
  const clipped = cleaned.slice(0, MAX_TITLE_LENGTH);
  const lastSpace = clipped.lastIndexOf(" ");
  const cut = lastSpace > MAX_TITLE_LENGTH / 2 ? clipped.slice(0, lastSpace) : clipped;
  return `${cut.replace(/[\s,;:.!?-]+$/, "")}…`;
}

/**
 * Accepts a generated title, or rejects it.
 *
 * Models asked for a bare name still wrap it in quotes, tack on a period, or
 * ignore the word limit and return a sentence. Null means the caller should
 * fall back rather than show any of that.
 */
export function sanitizeTitle(raw: string): string | null {
  const stripped = collapse(raw)
    // Some models answer `Title: Parental leave policy`.
    .replace(/^(?:title|name)\s*:\s*/i, "")
    .replace(/^["'“”‘’«»]+|["'“”‘’«»]+$/g, "")
    .replace(/[.]+$/, "")
    .trim();

  if (!stripped) return null;
  // A model that ignored the instruction returned prose, not a name. Its first
  // sentence is no better than the question, so the question wins.
  if (stripped.length > MAX_TITLE_LENGTH * 2) return null;
  return stripped.slice(0, MAX_TITLE_LENGTH);
}

function collapse(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

/** What the sidebar shows for a conversation that has no name yet. */
export function displayTitle(title: string | null | undefined): string {
  return title?.trim() || UNTITLED_CONVERSATION;
}
